<?php
  $kagi_token = FreshRSS_Context::$user_conf->kagi_token;
?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
  <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
  <p><?php echo _t('ext.kagiSummarizer.configure.kagi_token_help'); ?></p>
  <div class="form-group">
    <label class="group-name" for="kagi_token"><?php echo _t('ext.kagiSummarizer.configure.kagi_token'); ?></label>
    <div class="group-controls">
      <input type="text" name="kagi_token" id="kagi_token" value="<?php echo $kagi_token; ?>">
    </div>
  </div>
  <div class="form-group form-actions">
    <div class="group-controls">
      <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
    </div>
  </div>
</form>
